added message for permission deined exceptions
django-guardian/django-guardian pull request #720
Opened 2020-10-09 20:17 UTC by marxide

I found myself wanting to pass string to the `PermissionDenied` exceptions to that I could display more information to the user on the 403 page.

This PR adds an attribute `permission_denied_message` and an overridable method `get_permission_denied_message` to the PermissionRequiredMixin which can be configured with a message string that is passed to the PermissionDenied exception. By default, Django will then add the string representation of the `PermissionDenied` exception to the template context as `exception`.

If `permission_denied_message` is undefined, an empty string is passed to `PermissionDenied`.

Here are a couple of examples

1. Simple message.

If the current user does not have the `app_label.view_secretmodel` permission, they will be served the 403 page that contains the message "You do not have access to the request secret object.".

```python
# models.py
from django.db import models
from django.contrib.auth.models import User

class SecretModel(models.Model):
    name = models.CharField(max_length=30)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
```

```python
# views.py
from django.views.generic import DetailView
from guardian.mixins import PermissionRequiredMixin
from app_label.models import SecretModel

class SecretObjectDetail(PermissionRequiredMixin, DetailView):
    model = SecretModel
    permission_required = "app_label.view_secretmodel"
    raise_exception = True
    permission_denied_message = "You do not have access to the request secret object."
```

```html

{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
  <div class="alert alert-danger" role="alert">
    <h3 class="alert-heading">Permission Denied</h3>
    {{ exception|default:"You do not have permission to view this content." }}
  </div>
</div>
{% endblock content %}
```

2. More detailed message.

`models.py` and `403.html` as above.

```python
# views.py
from django.views.generic import DetailView
from guardian.mixins import PermissionRequiredMixin
from app_label.models import SecretModel

class SecretObjectDetail(PermissionRequiredMixin, DetailView):
    model = SecretModel
    permission_required = "app_label.view_secretmodel"
    raise_exception = True

    def get_permission_denied_message(self):
        obj = self.get_object()
        return (
            f"You do not have permission to view the secret object '{obj.name}'. "
            f"Please ask the owner, {obj.owner.username}, to grant you permission."
        )
```

2021-02-28 18:58 UTC, RainshawGao commented
@marxide In fact, there is still one place in `guardian/decorators` using the `get_40x_or_None`.  I think it would be better to modify the `permission_required` function.

2021-02-28 19:04 UTC, RainshawGao requested changes

2021-02-28 19:04 UTC, RainshawGao commented on guardian/mixins.py
> +        return message
And I think this function is a little complex.
In `django.contrib.auth.mixins.PermissionRequiredMixin`, we can find that it just return the `self.permission_denied_message`.
```
# in django/contrib/auth/mixins/PermissionRequiredMixin
    def get_permission_denied_message(self):
        """
        Override this method to override the permission_denied_message attribute.
        """
        return self.permission_denied_message
```

2021-02-28 19:04 UTC, RainshawGao commented on guardian/mixins.py
> +    permission_denied_message = None
We can make this be blank str `''`, and it would help with the `get_permission_denied_message` function to be simple.

2025-01-24 15:12 UTC, thclark commented
The review hasn't been responded to in a long time, so I'm going to close this PR to reduce noise. However, if folks deem the feature useful please file an issue first and we can resurrect if need be.

2025-01-24 15:12 UTC, closed without merging