get_groups_with_perms bug
django-guardian/django-guardian pull request #838
Opened 2024-12-28 10:01 UTC by okaluk

Hello,

in a project im working with, i discovered a bug.

When overriding the guardian-setting GROUP_OBJ_PERMS_MODEL with a custom model, we use the generic GroupObjectPermissionAbstract mixin to implement the custom model.

We use the get_groups_with_perms and when we want to get the perms attached, it crashes.

When investigating this crash, i discovered our custom model is checked against is GroupObjectPermission cannot be true even if it should be true because we dont have the content_object key inside our model. 

I build a testcase to show this bug in a pretty basic way. I already have the fix for this bug.

It would be nice, to run the CI to show that the bug exists, i would then push my fix to validate it fixes the testcases

Best Wishes,
Oguzhan Kaluk

2024-12-28 10:25 UTC, okaluk commented on guardian/testapp/testsettings.py
> +DEBUG = True
```suggestion
DEBUG = False
```
This is not intended and has to be reverted

2024-12-28 11:02 UTC, okaluk commented
i created a PR in my branch to run the pipeline:

Failing Tests:
https://github.com/okaluk/django-guardian/pull/2/checks?check_run_id=34938165970

Fixed Tests:
https://github.com/okaluk/django-guardian/pull/2/checks?check_run_id=34938201319

2024-12-28 11:17 UTC, BonaFideIT approved these changes
Thank you for finding the bug! Looks good for us.

2024-12-28 11:29 UTC, BonaFideIT commented
@thclark @brianmay please review this PR.

2025-01-04 07:26 UTC, brianmay approved these changes
I think I am not the right person to be reviewing this. But I don't see anything obviously wrong, so will approve.

2025-01-23 14:29 UTC, BonaFideIT approved these changes

2025-01-24 07:17 UTC, thclark commented
> > I think I am not the right person to be reviewing this. But I don't see anything obviously wrong, so will approve.
> 
> Is it possible to restore our write access? our second review does not seem to count, I guess this is due to not having sufficient rights?

I'll have a look!

2025-01-24 07:26 UTC, thclark commented
> > I think I am not the right person to be reviewing this. But I don't see anything obviously wrong, so will approve.
> 
> Is it possible to restore our write access? our second review does not seem to count, I guess this is due to not having sufficient rights?

Thanks @BonaFideIT - I think your access was reduced because you didn't have 2FA set up previously, and I overhauled the security policy to require it. I see that's no longer a problem so triggered an invitation to the reviewers team.

2025-01-24 07:31 UTC, thclark requested changes
~~This will break every user's CI on migration, leading to one hell of a mess, because it's dependent on a non-core app (@BonaFideIT even though I've added you please don't approve this!).~~

~~@okaluk Please can you outline in more detail the need for a migration and what you're trying to do here? Which issue does this PR address? If it's not against an issue, please can you raise an issue so we take it a step at a time to determine what problem this is solving and find a solution that won't break everyone's installations?~~

2025-01-24 07:31 UTC, thclark commented on guardian/testapp/migrations/0007_genericgroupobjectpermission.py
> +        ('testapp', '0006_auto_20230727_0658'),
I believe this will break everybody's migrations as `testapp` isn't a django app (something on your machine? Or the example app?)

2025-01-24 08:52 UTC, BonaFideIT commented on guardian/testapp/migrations/0007_genericgroupobjectpermission.py
> +        ('testapp', '0006_auto_20230727_0658'),
not sure what you are referring to. This app it the test app for running the tests. 

How will that break the CI? 

The testcases have all passed in this pull request? 

This migration depends on two standard django apps (contrib auth and contrib contenttypes) and on the "testapp" which is just the migration in the same app that already existed.

2025-01-24 10:19 UTC, thclark commented on guardian/testapp/migrations/0007_genericgroupobjectpermission.py
> +        ('testapp', '0006_auto_20230727_0658'),
@BonaFideIT I'm looking to find where testapp is imported, I think it'd be highly unusual to be adding an extra app into peoples production databases just for us to test guardian in our dev/CI. As far as I know this app shouldn't actually be registered in a production environment. If it *is*, then this PR might be OK but then that's a whole different architectural can of worms.

2025-01-24 10:58 UTC, thclark commented on guardian/testapp/migrations/0007_genericgroupobjectpermission.py
> +        ('testapp', '0006_auto_20230727_0658'),
I inspected my production database. The `testapp` app isn't registered and none of its tables appear, so I'm asusming migrations that depend on it being registered will fail. I'll recreate the error that I expect to get on migration.

2025-01-24 11:11 UTC, BonaFideIT commented on guardian/testapp/migrations/0007_genericgroupobjectpermission.py
> +        ('testapp', '0006_auto_20230727_0658'),
This is not a production issue. The app is used in the CI. The migrations is also just used in the CI. The part of code you quoted will never be executed in production. :) Thanks for looking into it.

2025-01-24 11:19 UTC, thclark commented on guardian/testapp/migrations/0007_genericgroupobjectpermission.py
> +        ('testapp', '0006_auto_20230727_0658'),
@BonaFideIT OMG You're right, I'm so sorry it's a migration in testapp itself!

OK no problem I'll actually merge this then. It'll make it into `3.0.0rc2`.

2025-01-24 11:20 UTC, thclark approved these changes

2025-01-24 11:21 UTC, merged

2025-01-24 11:56 UTC, BonaFideIT commented on guardian/testapp/migrations/0007_genericgroupobjectpermission.py
> +        ('testapp', '0006_auto_20230727_0658'),
cheers, thanks :)